### ISSUE TITLE
NEW Purchasable DataExtension

### ISSUE THREAD

**Issue by muskie9** [dynamic/silverstripe-foxy#1]
**Overview**
This DataExtension will have the minimum required functionality, fields and providers for any product that can be purchased. Additional DataExtensions will be extended from this class for specific product type fields and functionality. This is similar to Elemental's implementation of [ElementalAreasExtension](https://github.com/dnadesign/silverstripe-elemental/blob/master/src/Extensions/ElementalAreasExtension.php) and [ElementalPageExtension](https://github.com/dnadesign/silverstripe-elemental/blob/master/src/Extensions/ElementalPageExtension.php)

**Docs To Review**
[Standard Product Fields](https://docs.foxycart.com/v/2.0/products#standard_product_options)

**Extended Product Type Consideration**
- Shippable
  - A product that will require shipping information from the buyer
- Downloadable
  - A digital product that may have download limits or download link expiration
- Subscribable
  - A product that renews at a pre-defined interval
- Donatable
  - A product with no base cost, or pre-defined costs for the user to select from with an option to enter a unique value to donate.

**Requirements**
- Unique Product Code
- ReceiptTitle
- Available
- Options
- Orders

**Notable Methods**
- Recursive availability checking for both the main product and product options

**Comment by jsirish** [comment]
closed via #11
