### ISSUE TITLE
NEW ProductOptions

### ISSUE THREAD

**Issue by muskie9** [dynamic/silverstripe-foxy#10]
**Overview**
These are groups of options (i.e. color, size, etc.).

**Requirements**
- Title
- WeightModifier
- CodeModifier
- PriceModifier
- WeightModifierAction
- CodeModifierAction
- PriceModifierAction
- Available
- Sortable

**Reference**
[OptionItem](https://github.com/dynamic/foxystripe/blob/master/src/Model/OptionItem.php)

**Comment by jsirish** [comment]
**Proposal**

Product has_many OptionGroups (would prefer different name)

OptionGroups many_many ProductOptions

ProductOptions now become reusable, however the modifiers complicate things. We would leverage summary_fields on ProductOption to prominently display any applied modifiers to an option. This would make it easier to choose the correct existing ProductOption in the following scenario:

Store contains two different t-shirt styles. Both offer XXL, but for t-shirt A the cost is +$1.00. T-shirt B XXL is the same price as other sizes.

When I add t-shirt C, where the XXL costs the same as other sizes, I can select the existing XXL option without modifiers from the system.

This allows ProductOptions to be reused, and keeps the modifier functionality. This should result in much less content pop while leveraging existing functionality.

From a CMS UX, OptionGroups will be managed in a GridField_RelationEditor. Being a has_many, the only option would be to create new groups from the gridfield.

Editing an OptionGroup would allow editing the title, and add new or add existing ProductOptions. Options would be sortable.

**Discussion**

We could consider Product many_many OptionGroups, and allow whole groups to be reusable. Advantages include even less content pop, assuming products are similar across the system. Disadvantages include making it more difficult to select a group without being able to see any modifiers applied to ProductOptions from the add existing OptionGroup level. 

**Additional Thoughts**

It may be smart to do a name/title convention on OptionGroup, perhaps even ProductOption. Title would be what displays on the front end, while name (or Description) would be an internal note describing the OptionGroup - such as "sizes for standard t-shirts" or "sizes for premium t-shirts including price modifiers".
