### ISSUE TITLE
BUG Price Update js not updating the price

### ISSUE THREAD

**Issue by muskie9** [dynamic/silverstripe-foxy#34]

**Comment by jsirish** [comment]
https://github.com/dynamic/silverstripe-foxy/blob/master/client/src/javascript/product_options.js

This file in general could use an overhaul - we're no longer doing any "selection unavaiable" copy in the form or JS, it's now being done in an `AddToCartForm` include file. I imagine a lot of this code could be removed.

**Comment by muskie9** [comment]
The script seems to work as long as `submitPrice` is an ID on the html element holding the price. With this in mind, there is a bug in which a product option with no price modifier is deemed `undefined` in the script, effectively removing the price from the page. Tracking the html value of the `shownPrice` var provides a default fallback for cases where an option doesn't have a Price modifier attached.

It's still worth re-working to simplify the script a bit, but as it is very close to working order.
