### ISSUE TITLE
FEATURE FoxyHelper - Set Product Classes

### ISSUE THREAD

**Issue by jsirish** [dynamic/silverstripe-foxy#62]
**Is your feature request related to a problem? Please describe.**
We've run into issues with queries in add-on modules, trying to find records without a base class set when we have to query by a column other than ID - such as `Code` for the foxy-inventory class. SiteTree covers all page types, but only those records with Purchasable will have the `Code` field.

**Describe the solution you'd like**
Updates to the `FoxyHelper` class:
* private static `product_classes` to set an array of product pages (Product, Event, etc)
* a getter method to determine which classes have `Purchasable` extension applied (via the static)

This will allow us to query those specific classes by doing something like the following:
`SiteTree::get()->filter('Classname', $this->product_classes)`

**Comment by muskie9** [comment]
This is good, but just to note: with the `private static $product_classes` approach we discussed, we'll not rely on the `ClassInfo` to traverse classes, so this will run under the assumption that any class declared in the private static would be a descendent of `SiteTree` at this point. We'll need to note that. The filter portion of the query would then be something like `->filter('ClassName', FoxyHelper::config()->get('product_classes'))`.

We could do a method that double checks the validity of the classes listed which would check the following for safety:

- Does it in fact have the appropriate extension(s)
- Is it a subclass of `SiteTree`

**Comment by jsirish** [comment]
For reference - something like this  might work nicely:

https://github.com/isobar-nz/silverstripe-catalogmanager/blob/master/src/Extensions/CatalogPageExtension.php#L103
