### ISSUE TITLE
BUG Product validation is not working

### ISSUE THREAD

**Issue by jsirish** [dynamic/silverstripe-foxy#66]
**Describe the bug**
When adding/editing a ShippableProduct, Price, Code and FoxyCategoryID are not currently being required. If these fields aren't set, the AddToCartForm is unable to add the product to the cart.

**To Reproduce**
1. Create a product, do not set the fields above
2. Save/Publish successful
3. Click Add To Cart button on Product detail, cart loads but product has not been added

**Expected behavior**
CMS should require the above fields on save

**Additional context**
Validation is set on `Purchasable` and `Shippable`

**Comment by muskie9** [comment]
see silverstripe/silverstripe-framework#9260
