### ISSUE TITLE
BUG - values of 0 fail to hash properly due to being considered 'open' fields

### ISSUE THREAD

**Issue by mak001** [dynamic/silverstripe-foxy#87]
**Describe the bug**
When trying to create a product with the price of 0 instead of the validation returning `0||hash` it returns `price||hash`. This is due to the foxycart validation assuming it is an open (user editable) value.

**To Reproduce**
1. Create a new product
2. Enter anything for the SKU
3. Enter 0 for the Price
4. Save
5. Go to the page in the front end
6. Inspect the form and find the Price input

**Expected behavior**
Values of 0 that should not be editable by the user should return `0||hash` instead of `field_name||hash`.

**Additional Context**
Was creating a free product for a promotion that was to be added to the cart with the foxycart js.

**Possible solutions**
add an open flag to the `fc_hash_value` function in the `thirdparty/foxycart/foxycart.cart_validation.php` file.

**Comment by muskie9** [comment]
I ran across this as well and did `"0"` for the value and it seemed to work. It might be worth raising a ticket in the [FoxyCart repo](https://github.com/FoxyCart/FoxyCart-Cart-Validation--PHP)

**Comment by muskie9** [comment]
@mak001 does #88 cover products in the CMS that have a price of $0.00 as well?

**Comment by mak001** [comment]
it would, but i found a better way to fix the `fc_hash_value` method from thinking `"--OPEN--"` is equal to `0` or `""` in https://github.com/FoxyCart/FoxyCart-Cart-Validation--PHP/pull/16
